name: template-discord-bot-worker
workers:
- name: worker
  environment_slug: python
  github:
    repo: digitalocean/template-discord-bot-worker
    branch: main
    deploy_on_push: true
  source_dir: /
  build_command: "pip install -r requirements.txt"
  run_command: "python discord_bot.py"
  instance_count: 1
  envs:
    - key: DISCORD_TOKEN
      value: <REQUIRED>
      type: SECRET